{"uuid": "633c2b31-d9ec-4512-81c5-6854cf68c356", "children": ["ffa2cf07-427b-49d5-aae4-2c9a76df93d0"], "befores": [{"name": "android_app_management", "status": "broken", "statusDetails": {"message": "AttributeError: module 'utils.allure' has no attribute 'step'\n", "trace": "  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\Soft\\QA_Python\\qa_hmw19\\tests\\android_app\\conftest.py\", line 38, in android_app_management\n    with allure.step('Initialize Android app'):\n         ^^^^^^^^^^^\n"}, "start": 1737571383475, "stop": 1737571383475}], "start": 1737571383475, "stop": 1737571383573}